name: GitHub Actions Demo
on: [push]
jobs:
  Test-application:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install frontend dependencies
          working-directory: ./application/frontend
          run: npm i
        - name: Run Eslint and Prettier
          working-directory: ./application/frontend
          run: | 
            npm run lint
            npm run format
        - name: Test frontend
          working-directory: ./application/frontend
          run: |
            npm run test:unit
