name: GitHub Actions Demo
on: [push]
jobs:
  Check-application:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'feat:') || contains(github.event.head_commit.message, 'refactor:') || contains(github.event.head_commit.message, 'fix:') || contains(github.event.head_commit.message, 'test:') || contains(github.event.head_commit.message, 'debug(pipeline):')
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install frontend dependencies
          working-directory: ./application/frontend
          run: npm i
        # - name: Run Eslint and Prettier
        #   working-directory: ./application/frontend
        #   run: | 
        #     npm run lint
        #     npm run format
        # - name: Test frontend
        #   working-directory: ./application/frontend
        #   run: |
        #     npm run test:unit
        - name: setup git auth
          env:
            email: ${{ secrets.EMAIL }}
            username: $GITHUB_ACTOR
            access_token: ${{ secrets.TOKEN }}
          run: |
            git config --global credential.helper store
            echo "https://${access_token}:x-oauth-basic@github.com" > ~/.git-credentials
            git config --global user.email $email
            git config --global user.name $username
        - name: Build application
          run: |
            cd application/frontend
            # REPOSITORY_NAME="'/${GITHUB_REPOSITORY#*/}/'"
            NODE_ENV=production
            npm i
            npm run build
        - name: deploy to gh-pages
          run: |
            git add */dist/*
            git commit -m "🚀 Deploy id ${GITHUB_RUN_ID}"
            git push origin ${GITHUB_REF##*/}:gh-pages --force
