name: GitHub Actions Demo
run-name: Testing "run-name"
on: [push]
jobs:
  Test-application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test frontend
        run: npm run test:unit